### ISSUE TITLE
Upgrading to bootstrap 4.0 final

### ISSUE THREAD

**Issue by jnarowski** [creativetimofficial/vue-light-bootstrap-dashboard-pro#4]
Wondering if/when you'll upgrade to bootstrap 4.0 final, since it was just released. Not sure if there are any breaking changes or not.

**Comment by cristijora** [comment]
@jnarowski There are some breaking changes in the bootstrap 4 final release. Unfortunately, they had breaking changes in almost every minor release until 4.0. We will upgrade to the final as soon as the html version is updated as well to avoid double work.

**Comment by cristijora** [comment]
Fixed in 1.1.0 release. See [Changelog](https://github.com/creativetimofficial/vue-light-bootstrap-dashboard-pro/blob/master/CHANGELOG.md) and [migration guide](http://vuejs.creative-tim.com/vue-light-bootstrap-dashboard-pro/documentation/#/migration_guide). To get the new version go to [Downloads section](https://www.creative-tim.com/downloads) and redownload the product.
